services:
  pharmatail-backend:
    image: kevalsabhani/pharmatail-backend:latest
    container_name: pharmatail-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - pharmatail-db
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - pharmatail-network

  pharmatail-db:
    image: postgres:latest
    container_name: pharmatail-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pharmatail-network

volumes:
  db_data:

networks:
  pharmatail-network:
    driver: bridge