FROM golang:1.24.1-alpine

WORKDIR /app

# Install necessary dependencies
RUN apk add --no-cache git

# Install air for live reload
RUN go install github.com/air-verse/air@latest

# Copy and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

EXPOSE 8080

ENTRYPOINT ["air"]